### PR TITLE
Initialize ImageType at Build Time

### LINKED ISSUE #168: `UnsupportedFeatureException: An object of type 'org.apache.pdfbox.rendering.ImageType$2' was found in the image heap`
Native image build fails with 
```
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: An object of type 'org.apache.pdfbox.rendering.ImageType$2' was found in the image heap. This type, however, is marked for initialization at image run time for the following reason: classes are initialized at run time by default.
```

More info: https://github.com/quarkiverse/quarkus-tika/actions/runs/6794028039/job/18469822743

### PR DESCRIPTION
**Pull request by melloware**
@gastaldi just seeing if this works...

Fix #168

### CODE REVIEW

**Comment by gastaldi** [comment]
I did the same yesterday and got an image build deadlock, but maybe because I ran in an Ubuntu VM with 8Gb RAM

**Comment by melloware** [comment]
Looks like it worked today!

**Comment by gastaldi** [comment]
You need to test with the latest Quarkus 999-SNAPSHOT (as the ecosystem CI does). 

Maybe we can merge this and see how it goes

**Comment by melloware** [comment]
Oh right I forgot it's the nightly build. Let's merge and cross our fingers?

**Comment by gastaldi** [comment]
Grab some popcorn and let's sit back and watch: https://github.com/quarkiverse/quarkus-tika/actions/runs/6801700484/job/18493148295 :)

**Pull request merged**
