### PR TITLE
2.0.0 Release

### PR DESCRIPTION
**Pull request by melloware**

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Comment by gastaldi** [comment]
Maybe wait for the quarkus-poi release before releasing this?

**Comment by melloware** [comment]
good idea

**Comment by gastaldi** [comment]
Converted to draft to prevent accidental merging

**Comment by melloware** [comment]
Can't do from fork so closing this.

**Comment by gastaldi** [comment]
I'm adding you as a maintainer: https://github.com/quarkiverse/quarkiverse-devops/pull/139

**Pull request closed without merging**
