### PR TITLE
Docs icon-url

### PR DESCRIPTION
**Pull request by melloware**
add docs logo: https://www.apache.org/foundation/press/kit/poweredBy/Apache_PoweredBy.svg

### CODE REVIEW

**Comment by gastaldi** [comment]
Isn't https://tika.apache.org/tika.png better? Or the size doesn't fit?

**Comment by melloware** [comment]
Good question i didn't know if the docs site forced a size on the image like 150x150 so we can use SVG?  It probably
Should enforce a standard size?

But yeah I can change it. I was just using the Apache Logo for all Apache projects.

**Comment by gastaldi** [comment]
@holly-cummins what are the constraints for the `icon-url` again?

**Comment by melloware** [comment]
@gastaldi i can see it in the HTML they all get resized to 80x80.

```xml
<img layout="constrained" width="80" height="80" >
```

**Comment by holly-cummins** [comment]
There aren't many constraints. 

The framework resizes the original image to the right size, and it will also try and do a smart crop to turn rectangles into squares. So, for example, with Renarde, https://github.com/quarkiverse/quarkus-renarde, the social media preview is a rectangle but we can tell the fox is the most interesting bit, so we center that.

SVG images work when I test them manually.

**Comment by holly-cummins** [comment]
In the two images suggested by @gastaldi and @melloware, I would normally think the tika-specific one is better, but I'm not sure how the smart crop would handle that rectangle, since there's interesting stuff on both sides. And, in fact, the tika-specific-ness in the tika logo is just text saying "Apache Tika," which doesn't add much since the text below it will already say "Tika".

**Comment by holly-cummins** [comment]
(You can experiment with how things look by setting the social media preview on the github repo and asking me to respin the extensions page, if you like. It's a bit less permanent than doing a release ... )

**Comment by melloware** [comment]
All good points.  The only reason I like using the Apache SVG is because most of the Apache project have "lame" icons or logos in my opinion so better to just have a nice clean standard for Apache libs like Tika, Lucene, FreeMarker, etc.  Just my thought. :)

**Comment by gastaldi** [comment]
@melloware Once a day if I am not mistaken: https://github.com/quarkusio/extensions/blob/main/.github/workflows/build_and_publish.yml#L9-L10

**Comment by holly-cummins** [comment]
> @holly-cummins how often does that extensions site get regenerated? I updated quarkus-itext logo a few days ago but I am still not seeing the latest info there?

Hm, that's not right. It's static, so updates aren't instant, but we rebuild once a day. 

However, I've just checked, and the last few builds have failed. I normally get an email for dead builds, so I'm not sure why I didn't. 

I've built locally to check, and itext has a nice icon now, so hopefully once I sort out the main build it should be there. 

image

**Comment by melloware** [comment]
Thank you!

**Pull request merged**
