### PR TITLE
Release 2.0.0.CR1

### PR DESCRIPTION
**Pull request by zhfeng**

### CODE REVIEW

**Comment by zhfeng** [comment]
@gastaldi can you take a look at the release workflow? It looks like there is an issue when update the docs changes.

**Comment by gastaldi** [comment]
That seems outdated. Can you copy from https://github.com/quarkiverse/quarkus-poi/blob/main/.github/workflows/release.yml?

**Comment by zhfeng** [comment]
Yeah, I will do.

**Comment by zhfeng** [comment]
@gastaldi It is still failing. Any thought? should I restart  another release?
```
[release 8b669a4] Update stable version for documentation
 1 file changed, 1 insertion(+), 1 deletion(-)
Switched to branch 'main'
M	docs/modules/ROOT/pages/includes/quarkus-tika.adoc
Your branch is up to date with 'origin/main'.
error: cannot rebase: You have unstaged changes.
error: Please commit or stash them.
Error: Process completed with exit code 1.
0s

```

**Comment by gastaldi** [comment]
@zhfeng yes, I just merged the PR you created and the release succeeded 👍🏻

**Pull request merged**
