### PR TITLE
Update to tika 2

### PR DESCRIPTION
**Pull request by tpodg**
Based on https://github.com/quarkiverse/quarkus-tika/pull/38
Fixed logging exception

### CODE REVIEW

**Comment by tpodg** [comment]
There is still an exception when building native image locally:

```
Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing org.apache.xmlbeans.impl.xpath.XPathFactory.getCompiledPath(java.lang.String, org.apache.xmlbeans.XmlOptions, java.lang.String) 
Parsing context:
   at org.apache.xmlbeans.impl.xpath.XPathFactory.getCompiledPath(XPathFactory.java:62)
   at org.apache.xmlbeans.impl.xpath.XPathFactory.getCompiledPath(XPathFactory.java:58)
   at org.apache.xmlbeans.impl.store.Cursor._selectPath(Cursor.java:715)
   at org.apache.xmlbeans.impl.store.Cursor.lambda$selectPath$20(Cursor.java:2026)
```

@gsmet Any suggestion on how to tackle this? 
I was also hoping for a build for this PR, could it be triggered manually?

**Comment by gastaldi** [comment]
@tpodg thanks for the PR. I picked your changes and merged them with mine (basically the major change is that it is using the `tika-bom`) and pushed them to an `update` branch.
 
Would you be interested in becoming a maintainer of this repository?

**Comment by tpodg** [comment]
I would have nothing against it, but to be honest, I have to dig a bit deeper into development of Quarkus extensions and especially GraalVM specifics related to native builds. There are some parts I would like to understand a better.

**Comment by gastaldi** [comment]
No problem. I made you a maintainer of this repository and you should be able to push to the `update` branch.

I am closing this PR can be closed now, let's continue the work there

**Pull request closed without merging**
