### PR TITLE
Fix #109 to remove vorbis-java-tika since it depends on tika 1.x

### LINKED ISSUE #109: vorbis-java-tika depend on tika 1.x
Since the `main` branch upgrade to `tika` 2.7.0 now, I wonder if we can remove `vorbis-java-tika` or mark it as `provided` at least.

### PR DESCRIPTION
**Pull request by zhfeng**

### CODE REVIEW

**Comment by gastaldi** [comment]
Although I understand why, I'd like to understand the reason behind this change.

**Comment by zhfeng** [comment]
Well, I got some enforcer WARN messages when building `camel-quarkus-tika` like
```
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-java-version) @ camel-quarkus-tika ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (camel-quarkus-enforcer-rules) @ camel-quarkus-tika ---
[WARNING] 
Dependency convergence error for org.apache.tika:tika-core:2.7.0 paths to dependency are:
+-org.apache.camel.quarkus:camel-quarkus-tika:3.0.0-SNAPSHOT
  +-org.apache.camel:camel-tika:4.0.0-M2
    +-org.apache.tika:tika-core:2.7.0
and
+-org.apache.camel.quarkus:camel-quarkus-tika:3.0.0-SNAPSHOT
  +-io.quarkiverse.tika:quarkus-tika:2.0.0.CR1
    +-org.apache.tika:tika-core:2.7.0
and
+-org.apache.camel.quarkus:camel-quarkus-tika:3.0.0-SNAPSHOT
  +-io.quarkiverse.tika:quarkus-tika:2.0.0.CR1
    +-org.gagravarr:vorbis-java-tika:0.8
      +-org.apache.tika:tika-core:1.12

[WARNING] Rule 1: org.apache.maven.plugins.enforcer.DependencyConvergence failed with message:
Failed while enforcing releasability. See above detailed error message.
```

I can  exclude these artifacts in `camel-quarkus-tika` as a work around but still want to know if it is possible to fix in `quarkus-tika`.

**Comment by zhfeng** [comment]
OK, I will update the PR to remove them. And see if there is any opposition from other persons.

**Review by gastaldi — APPROVED** [review]

**Comment by gastaldi** [comment]
I think we should backport this to the 1.x branch too

**Pull request merged**
